### PR TITLE
Add description of building a project using figwheel.

### PR DESCRIPTION
**Pull request by jdeisenberg**

### CODE REVIEW

**Comment by niwinz** [comment]
Good work! Thanks!

In any case  I prefer this kind of things in a mixed bag section. Figwheel is slightly opinionated and its usage is optional (as example, I don't use it on my projects). The compiler section is for explain the compiler basics and dependencies management.

**Comment by jdeisenberg** [comment]
Do you want me to move the text over to that section, then? 

Also, I think you definitely should refer to chapter 4 near the beginning of chapter 3. In section 4.1, you say "At this point, you are surely very bored with the constant theoretical explanations about the language itself and will want to write and execute some code." I can't imagine anyone with the patience to read all of the *very* long chapter 3 without having some way to try it for themselves.

**Comment by niwinz** [comment]
You are right,  but chapter 3 should explain how the basic tooling and compiler works, such as leiningen... and plain compiler. figweel is a third party plugin that you can use and can not.

Because of it, I prefer figweel subchapter in the mixed bag. The similar subchapter sould be done in the chapter 3 but using only basic tooling, such as leiningen. 

This book is intended to be incremental, and introducing figwheel in a compiler makes figwheel a defacto standard for compile clojurescript and it is not.

**Comment by dialelo** [comment]
I rebased these commits, moved the chapter and pushed it to a [branch](https://github.com/funcool/clojurescript-unraveled/tree/repl-driven-development-with-figwheel). @jdeisenberg you can reset to branch to that commit.

>Also, I think you definitely should refer to chapter 4 near the beginning of chapter 3. In section 4.1, you say "At this point, you are surely very bored with the constant theoretical explanations about the language itself and will want to write and execute some code." I can't imagine anyone with the patience to read all of the very long chapter 3 without having some way to try it for themselves.

You are right, I think we should link the section on figwheel from the more thorough compiler chapter. Having the compiler & tooling information as a reference is great but we should provide a quick start step for people that want to try things right away, one of Lisp's great things is the interactive development after all.

**Comment by niwinz** [comment]
Already merged! Thanks!

**Pull request closed without merging**
