### PR TITLE
Core protocols part 2

### PR DESCRIPTION
**Pull request by dialelo**
This is a PR for writing the rest of the Core protocols section, still a work in progress.

### CODE REVIEW

**Comment by dialelo** [comment]
@niwinz please take a look and merge if you think it's OK. There are still some protocols commented out since I'm not sure it's worth talking about them, would appreaciate feedback on that regard.

**Comment by niwinz** [comment]
Sure, I'll try to do it later or tomorrow!

**Comment by niwinz** [comment]
I completly forgotten about this, sorry! I will do it today.

**Comment by niwinz** [comment]
It is fine for me! thanks!

**Pull request merged**
